import ExternalLinks from '@/components/ExternalLinks'
import CheckLayout from '@/layouts/CheckLayout'
import { CATEGORIES } from '@/routes/categories'
import type { Metadata } from 'next'

const category = CATEGORIES['carbon-footprint']

export const metadata: Metadata = {
  title: category.title,
  description: category.description
}

export default function PageCarbonFootprint() {
  return (
    <CheckLayout category={category}>
      <article>
        <h2>What is Carbon Footprint?</h2>

        <p>
          A carbon footprint is the total amount of greenhouse gases (including
          carbon dioxide and methane) that are generated by our actions. It is
          usually expressed in equivalent tons of carbon dioxide (CO2e) per
          year.
        </p>

        <p>
          The Web has a carbon footprint too, and it is estimated to be around
          3.7% of global greenhouse gas emissions. This includes the energy
          consumption of data centers, network infrastructure, and end-user
          devices.
        </p>

        <p>
          Check the carbon footprint of websites above and learn more bellow.
        </p>

        <h3>Resources</h3>

        <ExternalLinks
          links={[
            {
              url: 'https://www.carbonfootprint.com/',
              text: 'CarbonFootprint.com'
            },
            {
              url: 'https://www.nature.org/en-us/get-involved/how-to-help/carbon-footprint-calculator/',
              text: 'Nature.org Carbon Footprint Calculator'
            },
            {
              url: 'https://www.epa.gov/carbon-footprint-calculator/',
              text: 'EPA Carbon Footprint Calculator'
            }
          ]}
        />
      </article>
    </CheckLayout>
  )
}
